name: uoc20241pec3
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib=3.9.2
  - jupyter=1.0.0
  - tqdm=4.66.5
  - scipy=1.13.1
  - scikit-learn=1.5.1
  - numpy=1.26.4
  - pip=24.2
  - python=3.11.10
  - pytorch=2.3.1
  - kagglehub=0.3.4
  - pandas=2.2.3
  - shap=0.46.0
  - seaborn=0.13.2
  - pip:
    - umap-learn==0.5.6
    - torcheval==0.0.7
